version: '3.1'

services:

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    networks:
      backend:

  web:
    image: nginx
    container_name: web
    depends_on:
      - pdf
    ports: 
      - 8080:80
    volumes:
      - //c/kuali/kc/coeus-impl/src/main/resources/org/kuali/kra/subawardReporting/printing/print://usr/share/nginx/html:rw
      - //c/whennemuth/kuali-research-docker/research-pdf/build.context/nginx-pdf.conf://etc/nginx/conf.d/default.conf
    networks:
      backend:

  pdf:
    image: 730096353738.dkr.ecr.us-east-1.amazonaws.com/research-pdf:2107.0004
    container_name: research-pdf
    depends_on: 
      - db
    ports:
      - 3006:3006
    environment:
      AUTH_ENABLED: 'false'
      AWS_S3_ENABLED: 'false'
      MONGO_ENABLED: 'true'
      SPRING_DATA_MONGODB_URI: 'mongodb://db:27017'
      SPRING_DATA_MONGODB_DATABASE: 'jobs'
    networks:
      backend:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.8.0.0/16
