version: '3.1'

services:

  pdf:
    # image: 'wrh1/research-pdf'
    image: '730096353738.dkr.ecr.us-east-1.amazonaws.com/research-pdf:2107.0004'
    restart: unless-stopped
    container_name: 'research-pdf'
    ports:
      - 3006:3006
    volumes:
      - //c/kuali/kc/coeus-impl/src/main/resources/org/kuali/kra/subawardReporting/printing/print/fdpAgreement.pdf://tmp/test.pdf
    environment:
      AUTH_ENABLED: 'false'
      MONGO_ENABLE: 'false'
      AWS_S3_ENABLE: 'false'
      # AUTH_ENABLED: 'true'
      # AUTH_BASEURL: 'https://kuali-research-sb.bu.edu'
      # AUTH_SERVICE2SERVICE_SECRETS: 'kc.service.secret.kc.service.secret.kc.service.secret.kc.service.secret'
      # MONGO_ENABLED: 'true'
      # SPRING_DATA_MONGODB_URI: 'mongodb+srv://admin:[url-encoded password]@sb-cluster-ozx2o.mongodb.net/test?retryWrites=true&w=majority'
      # AWS_REGION: 'us-east-1'
      # AWS_S3_ENABLED: 'true'
      # AWS_S3_BUCKET: 'kuali-research-pdf-sb'
