-- Title : QA Tools #1 - Saved Proposal Documents
-- Desc  : Report of all institutional proposal documents in a saved state
-- By    : Bennett Gavrish 6/6/2013

SELECT
  PROPOSAL.DOCUMENT_NUMBER                AS "DOC NUMBER",
  PROPOSAL.PROPOSAL_NUMBER                AS "PROPOSAL NUMBER",
  PROPOSAL.SEQUENCE_NUMBER                AS "VERSION",
  KRIM_PRNCPL_T.PRNCPL_NM                 AS "INITIATOR",
  PROPOSAL.CREATE_TIMESTAMP               AS "CREATION DATE",
  PROPOSAL_TYPE.DESCRIPTION               AS "PROPOSAL TYPE",
  ACTIVITY_TYPE.DESCRIPTION               AS "ACTIVITY TYPE",
  PROPOSAL_STATUS.DESCRIPTION             AS "STATUS",
  PROPOSAL.LEAD_UNIT_NUMBER               AS "LEAD UNIT",
  UNIT.UNIT_NAME                          AS "LEAD UNIT NAME",
  PROPOSAL.CURRENT_ACCOUNT_NUMBER         AS "ACCOUNT",
  PROPOSAL.TITLE                          AS "PROJECT TITLE",
  PROPOSAL.SPONSOR_CODE                   AS "SPONSOR ID",
  SPONSOR.SPONSOR_NAME                    AS "SPONSOR NAME",
  PRIME_SPONSOR.SPONSOR_NAME              AS "PRIME SPONSOR",
  PROPOSAL_PERSONS.FULL_NAME              AS "PRINCIPAL INVESTIGATOR",
  PROPOSAL.FISCAL_YEAR                    AS "FISCAL YEAR",
  PROPOSAL.FISCAL_MONTH                   AS "FISCAL MONTH",
  PROPOSAL.REQUESTED_START_DATE_INITIAL   AS "INITAL REQUESTED START DATE",
  PROPOSAL.REQUESTED_START_DATE_TOTAL     AS "TOTAL REQUESTED START DATE",
  PROPOSAL.REQUESTED_END_DATE_INITIAL     AS "INITIAL REQUESTED END DATE",
  PROPOSAL.REQUESTED_END_DATE_TOTAL       AS "TOTAL REQUESTED END DATE",
  PROPOSAL.TOTAL_DIRECT_COST_INITIAL      AS "INITIAL TOTAL DIRECT COST",
  PROPOSAL.TOTAL_DIRECT_COST_TOTAL        AS "TOTAL TOTAL DIRECT COST",
  PROPOSAL.TOTAL_INDIRECT_COST_INITIAL    AS "INITIAL F+A COST",
  PROPOSAL.TOTAL_INDIRECT_COST_TOTAL      AS "TOTAL F+A COST"

FROM KCOEUS.PROPOSAL
  ---Joining from PROPOSAL table selects only proposal documents
  INNER JOIN kcoeus.KREW_DOC_HDR_T ON KREW_DOC_HDR_T.DOC_HDR_ID = PROPOSAL.DOCUMENT_NUMBER
  LEFT JOIN KCOEUS.PROPOSAL_TYPE ON PROPOSAL.PROPOSAL_TYPE_CODE = PROPOSAL_TYPE.PROPOSAL_TYPE_CODE
  LEFT JOIN KCOEUS.ACTIVITY_TYPE ON PROPOSAL.ACTIVITY_TYPE_CODE = ACTIVITY_TYPE.ACTIVITY_TYPE_CODE
  LEFT JOIN KCOEUS.PROPOSAL_STATUS ON PROPOSAL.STATUS_CODE = PROPOSAL_STATUS.PROPOSAL_STATUS_CODE
  LEFT JOIN KCOEUS.UNIT ON PROPOSAL.LEAD_UNIT_NUMBER = UNIT.UNIT_NUMBER
  LEFT JOIN KCOEUS.SPONSOR ON PROPOSAL.SPONSOR_CODE = SPONSOR.SPONSOR_CODE
  LEFT JOIN (SELECT * FROM KCOEUS.SPONSOR) PRIME_SPONSOR ON PROPOSAL.PRIME_SPONSOR_CODE = PRIME_SPONSOR.SPONSOR_CODE
  LEFT JOIN KCOEUS.PROPOSAL_PERSONS ON PROPOSAL.PROPOSAL_ID = PROPOSAL_PERSONS.PROPOSAL_ID
  LEFT JOIN kcoeus.KRIM_PRNCPL_T ON KREW_DOC_HDR_T.INITR_PRNCPL_ID = KRIM_PRNCPL_T.PRNCPL_ID

WHERE KREW_DOC_HDR_T.DOC_HDR_STAT_CD = 'S'
  AND PROPOSAL_PERSONS.CONTACT_ROLE_CODE = 'PI'

ORDER BY PROPOSAL.PROPOSAL_NUMBER
;

-- An EXIT statement must be present at end of each SQL script. 
-- It tells SQLcl subprocess launched by Python that its job is done.
-- If missing, SQLcl subprocess will wait for the next instruction, which never comes.   
EXIT;