-- Title : QA Tools #3 - Saved Time & Money Documents
-- Desc  : Report of all time and money documents in a saved state
-- By    : Bennett Gavrish 6/18/2013

SELECT
  TIME_AND_MONEY_DOCUMENT.DOCUMENT_NUMBER                           AS "DOC NUMBER",
  TIME_AND_MONEY_DOCUMENT.AWARD_NUMBER                              AS "AWARD NUMBER",
  AWARD_TRANSACTION_TYPE.DESCRIPTION                                AS "TRANSACTION TYPE",
  KRIM_PRNCPL_T.PRNCPL_NM                                           AS "INITIATOR",
  TIME_AND_MONEY_DOCUMENT.UPDATE_TIMESTAMP                          AS "LAST UPDATED",
  KREW_DOC_HDR_T.CRTE_DT                                            AS "CREATION DATE",
  AWARDS_MAXSEQ.DFAFS_NUMBER                                        AS "SPONSOR AWARD ID",
  AWARDS_MAXSEQ.LEAD_UNIT_NUMBER                                    AS "LEAD UNIT ID",
  UNIT.UNIT_NAME                                                    AS "LEAD UNIT",
  AWARDS_MAXSEQ.ACCOUNT_NUMBER                                      AS "ACCOUNT ID",
  AWARD_STATUS.DESCRIPTION                                          AS "AWARD STATUS",
  AWARDS_MAXSEQ.TITLE                                               AS "AWARD TITLE",
  AWARDS_MAXSEQ.SPONSOR_CODE                                        AS "SPONSOR ID",
  SPONSOR.SPONSOR_NAME                                              AS "SPONSOR NAME",
  AWARD_PERSONS.FULL_NAME                                           AS "INVESTIGATOR",
  KRIM_ENTITY_NM_T.FIRST_NM || ' ' || KRIM_ENTITY_NM_T.LAST_NM      AS "OSP ADMIN",
  AAI.FINAL_EXPIRATION_DATE                                         AS "PROJECT END DATE"

FROM kcoeus.KREW_DOC_HDR_T
  ---Joining to TIME_AND_MONEY_DOCUMENT table selects only time and money documents
  INNER JOIN KCOEUS.TIME_AND_MONEY_DOCUMENT ON KREW_DOC_HDR_T.DOC_HDR_ID = TIME_AND_MONEY_DOCUMENT.DOCUMENT_NUMBER
  INNER JOIN SAPBWKCRM.AWARDS_MAXSEQ ON TIME_AND_MONEY_DOCUMENT.AWARD_NUMBER = AWARDS_MAXSEQ.AWARD_NUMBER
  LEFT JOIN KCOEUS.AWARD_TRANSACTION_TYPE ON AWARDS_MAXSEQ.TRANSACTION_TYPE_CODE = AWARD_TRANSACTION_TYPE.AWARD_TRANSACTION_TYPE_CODE
  LEFT JOIN KCOEUS.UNIT ON AWARDS_MAXSEQ.LEAD_UNIT_NUMBER = UNIT.UNIT_NUMBER
  LEFT JOIN KCOEUS.AWARD_STATUS ON AWARDS_MAXSEQ.STATUS_CODE = AWARD_STATUS.STATUS_CODE
  LEFT JOIN KCOEUS.SPONSOR ON AWARDS_MAXSEQ.SPONSOR_CODE = SPONSOR.SPONSOR_CODE
  LEFT JOIN KCOEUS.AWARD_PERSONS ON AWARDS_MAXSEQ.AWARD_ID = AWARD_PERSONS.AWARD_ID
  LEFT JOIN KCOEUS.UNIT_ADMINISTRATOR ON UNIT.UNIT_NUMBER = UNIT_ADMINISTRATOR.UNIT_NUMBER
  INNER JOIN kcoeus.KRIM_ENTITY_NM_T ON UNIT_ADMINISTRATOR.PERSON_ID = KRIM_ENTITY_NM_T.ENTITY_ID
  LEFT JOIN kcoeus.KRIM_PRNCPL_T ON KREW_DOC_HDR_T.INITR_PRNCPL_ID = KRIM_PRNCPL_T.PRNCPL_ID
  ---Joining only on the latest AWARD_AMOUNT_INFO record
  LEFT JOIN KCOEUS.AWARD_AMOUNT_INFO AAI
                           INNER JOIN (SELECT AWARD_ID, MAX(AWARD_AMOUNT_INFO_ID) AS MAXAMOUNTID
                                        FROM KCOEUS.AWARD_AMOUNT_INFO
                                        GROUP BY AWARD_ID) MAXAMOUNTINFO
                                  ON (AAI.AWARD_ID = MAXAMOUNTINFO.AWARD_ID AND AAI.AWARD_AMOUNT_INFO_ID = MAXAMOUNTINFO.MAXAMOUNTID)
           ON AWARDS_MAXSEQ.AWARD_ID = AAI.AWARD_ID

WHERE KREW_DOC_HDR_T.DOC_HDR_STAT_CD = 'S'
  AND AWARD_PERSONS.CONTACT_ROLE_CODE = 'PI'
  AND UNIT_ADMINISTRATOR.UNIT_ADMINISTRATOR_TYPE_CODE = '3'
  AND KRIM_ENTITY_NM_T.DFLT_IND = 'Y'
  AND AWARD_STATUS.DESCRIPTION != 'Cancelled'

ORDER BY TIME_AND_MONEY_DOCUMENT.AWARD_NUMBER
;

-- An EXIT statement must be present at end of each SQL script. 
-- It tells SQLcl subprocess launched by Python that its job is done.
-- If missing, SQLcl subprocess will wait for the next instruction, which never comes.   
EXIT;