-- Title : QA Tools #7 - External Parent Transactions
---Desc  : Report of all external transactions sent to parent awards
---By    : Bennett Gavrish, 6/26/2013
-- Change: Dean Haywood  9/2/2014  Altered SAPBWKCRM view from AAI_AAT_MAXSEQ_PRE_GROUPING to AAI_AAT after KC 5.2 conversion

SELECT
  PENDING_TRANSACTIONS.DOCUMENT_NUMBER                            AS "DOC NUMBER",
  PENDING_TRANSACTIONS.TRANSACTION_ID                             AS "TRANSACTION ID",
  PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER                   AS "DESTINATION AWARD NUMBER",
  PENDING_TRANSACTIONS.OBLIGATED_AMOUNT                           AS "AMOUNT OBLIGATED",
  PENDING_TRANSACTIONS.ANTICIPATED_AMOUNT                         AS "AMOUNT ANTICIPATED",
  AWARD_TRANSACTION_TYPE.DESCRIPTION                              AS "TRANSACTION TYPE",
  PENDING_TRANSACTIONS.UPDATE_TIMESTAMP                           AS "LAST UPDATED"

FROM KCOEUS.PENDING_TRANSACTIONS
  LEFT JOIN SAPBWKCRM.AAI_AAT ON (PENDING_TRANSACTIONS.DOCUMENT_NUMBER = AAI_AAT.TNM_DOCUMENT_NUMBER
                                                      AND PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER = AAI_AAT.AWARD_NUMBER
                                                      AND PENDING_TRANSACTIONS.TRANSACTION_ID = AAI_AAT.TRANSACTION_ID)
  LEFT JOIN SAPBWKCRM.AWARDS_MAXSEQ ON PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER = AWARDS_MAXSEQ.AWARD_NUMBER
  LEFT JOIN KCOEUS.AWARD_TRANSACTION_TYPE ON AAI_AAT.TRANSACTION_TYPE_CODE = AWARD_TRANSACTION_TYPE.AWARD_TRANSACTION_TYPE_CODE

WHERE PENDING_TRANSACTIONS.SOURCE_AWARD_NUMBER = '000000-00000'
  AND PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER LIKE '%-00001'
  AND PENDING_TRANSACTIONS.OBLIGATED_AMOUNT <> 0
  AND AAI_AAT.TRANSACTION_TYPE_CODE IN (2,3,4,5,8,11)
  AND AWARDS_MAXSEQ.STATUS_CODE != 9

ORDER BY PENDING_TRANSACTIONS.DOCUMENT_NUMBER
;

-- An EXIT statement must be present at end of each SQL script. 
-- It tells SQLcl subprocess launched by Python that its job is done.
-- If missing, SQLcl subprocess will wait for the next instruction, which never comes.   
EXIT;