-- Title : QA Tools #8 - Negative Transactions
-- Desc  : Transactions where Child to External has negative obligated change and
--         type is New, Continuation, Supplement, Increment, or Renewal
-- By    : Bennett Gavrish 6/6/2013
-- Change: D.Haywood   11/08/2013  added calculated date for prior month's records

SELECT
AAI.TNM_DOCUMENT_NUMBER,
AAI.AWARD_AMOUNT_INFO_ID,
AAI.AWARD_ID,
AAI.AWARD_NUMBER,
AAI.SEQUENCE_NUMBER,
AAI.TRANSACTION_ID,
AAI.UPDATE_USER,
AAI.OBLIGATED_CHANGE,
AAI.OBLIGATED_CHANGE_DIRECT,
AAI.OBLIGATED_CHANGE_INDIRECT,
AAI.UPDATE_TIMESTAMP,
A_A_T.TRANSACTION_TYPE_CODE,
AWARD_TRANSACTION_TYPE.DESCRIPTION AS "TRANSACTION TYPE",
PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER,
PENDING_TRANSACTIONS.source_award_number

FROM SAPBWKCRM.AWARDS_MAXSEQ

LEFT JOIN KCOEUS.AWARD_AMOUNT_INFO AAI
                   INNER JOIN (SELECT AWARD_ID, MAX(AWARD_AMOUNT_INFO_ID) AS MAXAMOUNTID
                                FROM KCOEUS.AWARD_AMOUNT_INFO
                                GROUP BY AWARD_ID) MAXAMOUNTINFO
                          ON (AAI.AWARD_ID = MAXAMOUNTINFO.AWARD_ID AND AAI.AWARD_AMOUNT_INFO_ID = MAXAMOUNTINFO.MAXAMOUNTID)
   ON AWARDS_MAXSEQ.AWARD_ID = AAI.AWARD_ID

LEFT JOIN KCOEUS.PENDING_TRANSACTIONS ON AAI.TRANSACTION_ID = PENDING_TRANSACTIONS.TRANSACTION_ID
LEFT JOIN KCOEUS.TIME_AND_MONEY_DOCUMENT ON TIME_AND_MONEY_DOCUMENT.DOCUMENT_NUMBER  = AAI.TNM_DOCUMENT_NUMBER
LEFT JOIN SAPBWKCRM.A_A_T ON (AAI.TNM_DOCUMENT_NUMBER = A_A_T.TRANSACTION_ID AND AAI.AWARD_NUMBER = A_A_T.AWARD_NUMBER)
LEFT JOIN KCOEUS.AWARD_TRANSACTION_TYPE AWARD_TRANSACTION_TYPE
                           ON (A_A_T.TRANSACTION_TYPE_CODE =
                                  AWARD_TRANSACTION_TYPE.AWARD_TRANSACTION_TYPE_CODE)
WHERE A_A_T.TRANSACTION_TYPE_CODE IN('2','3','4','5','8')
AND PENDING_TRANSACTIONS.DESTINATION_AWARD_NUMBER = '000000-00000'
AND SUBSTR(AAI.AWARD_NUMBER,8,5) = '00001'
AND AAI.OBLIGATED_CHANGE < 0
AND TO_CHAR(TIME_AND_MONEY_DOCUMENT.UPDATE_TIMESTAMP,'YYYYMMDD') BETWEEN TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-2)+1,'YYYYMMDD') -- first day of prior month
                                                                     AND TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-1),'YYYYMMDD')   -- last day of prior month
ORDER BY AAI.AWARD_NUMBER
;

-- An EXIT statement must be present at end of each SQL script. 
-- It tells SQLcl subprocess launched by Python that its job is done.
-- If missing, SQLcl subprocess will wait for the next instruction, which never comes.   
EXIT;