-- Title : QA Tools #9 - Miscoded Transactions
-- Desc  : Identify potential incorrect transaction types on PAFO award maintenance.
-- By    : Bennett Gavrish 6/6/2013
-- Change: D.Haywood   11/08/2013  added calculated date for 1st day of prior month

SELECT

AWARDS_MAXSEQ.AWARD_NUMBER                          AS "AWARD NUMBER",
AWARDS_MAXSEQ.LEAD_UNIT_NUMBER                      AS "LEAD UNIT",
AWARDS_MAXSEQ.TITLE                                 AS "TITLE",
AWARDS_MAXSEQ.SEQUENCE_NUMBER                       AS "VERSION NUMBER",
AWARDS_MAXSEQ.SPONSOR_CODE                          AS "SPONSOR CODE",
SPONSOR.SPONSOR_NAME                                AS "SPONSOR NAME",
AAI.TNM_DOCUMENT_NUMBER                             AS "TIME + MONEY DOC",
AAI.TRANSACTION_ID                                  AS "TRANSACTION ID",
AAI.OBLIGATED_CHANGE_DIRECT                         AS "OBLIGATED CHANGE DIRECT",
AAI.OBLIGATED_CHANGE_INDIRECT                       AS "OBLIGATED CHANGE INDIRECT",
AWARD_TRANSACTION_TYPE.DESCRIPTION                  AS "TRANSACTION TYPE",
TO_CHAR(TIME_AND_MONEY_DOCUMENT.UPDATE_TIMESTAMP, 'YYYYMMDD')          AS "TIME + MONEY CREATED ON"

FROM SAPBWKCRM.AWARDS_MAXSEQ

LEFT JOIN KCOEUS.AWARD_AMOUNT_INFO AAI
                   INNER JOIN (SELECT AWARD_ID, MAX(AWARD_AMOUNT_INFO_ID) AS MAXAMOUNTID
                                FROM KCOEUS.AWARD_AMOUNT_INFO
                                GROUP BY AWARD_ID) MAXAMOUNTINFO
                          ON (AAI.AWARD_ID = MAXAMOUNTINFO.AWARD_ID AND AAI.AWARD_AMOUNT_INFO_ID = MAXAMOUNTINFO.MAXAMOUNTID)
   ON AWARDS_MAXSEQ.AWARD_ID = AAI.AWARD_ID

LEFT JOIN SAPBWKCRM.A_A_T ON (AAI.TNM_DOCUMENT_NUMBER = A_A_T.TRANSACTION_ID AND AAI.AWARD_NUMBER = A_A_T.AWARD_NUMBER)
LEFT JOIN KCOEUS.AWARD_TRANSACTION_TYPE ON A_A_T.TRANSACTION_TYPE_CODE = AWARD_TRANSACTION_TYPE.AWARD_TRANSACTION_TYPE_CODE
LEFT JOIN KCOEUS.SPONSOR ON AWARDS_MAXSEQ.SPONSOR_CODE = SPONSOR.SPONSOR_CODE
LEFT JOIN KCOEUS.TIME_AND_MONEY_DOCUMENT ON TIME_AND_MONEY_DOCUMENT.DOCUMENT_NUMBER  = AAI.TNM_DOCUMENT_NUMBER

WHERE A_A_T.TRANSACTION_TYPE_CODE NOT IN('4','9')
  AND (SPONSOR.DODAC_NUMBER = '2550000013' OR SUBSTR(AWARDS_MAXSEQ.LEAD_UNIT_NUMBER,1,3) IN ('115','116','255'))
  AND TO_CHAR(TIME_AND_MONEY_DOCUMENT.UPDATE_TIMESTAMP, 'YYYYMMDD') >= TO_CHAR(ADD_MONTHS(LAST_DAY(SYSDATE),-2)+1,'YYYYMMDD') -- first day of prior month
  AND SUBSTR(AWARDS_MAXSEQ.AWARD_NUMBER,8,5) != '00001'

ORDER BY AWARDS_MAXSEQ.AWARD_NUMBER
;

-- An EXIT statement must be present at end of each SQL script. 
-- It tells SQLcl subprocess launched by Python that its job is done.
-- If missing, SQLcl subprocess will wait for the next instruction, which never comes.   
EXIT;